### PR TITLE
Added the "Development & Technology Scotland" Slack Channel to resources

### PR DESCRIPTION
**Pull request by b099l3**

### CODE REVIEW

**Comment by dougaitken** [comment]
Hey @b099l3 

On the surface, this sounds great - a Slack community for tech in Scotland. 

Can I ask you to provide more information about this, please? The root domain doesn't work, the sub-site is a branded URL redirect, and the full link redirects to a random email signup field hosted on AWS.

**Comment by b099l3** [comment]
Sorry, I don't own this domain or any of the AWS email signup; I am just a member of this slack.

I assume it is done this way to avoid needing a new invite link every 30 days, as they expire. The email sign-up seems to be using [zappa-slack-inviter](https://github.com/Miserlou/zappa-slack-inviter), the link at the bottom of the page.

@rawkode owns the domain based on this chat I had before adding the slack invite link to Awesome Edinburgh / Glasgow / Dundee.
image

So he might have some more info. That's all I know.

**Comment by bazwilliams** [comment]
Hi!

I'm one of the admins of the devtech scot Slack channel :)

Unfortunately, there's no way to sign up to the Dev Tech Scotland Slack without an invitation (https://devtechscot.slack.com)

So when we first set the slack up, we configured a lambda which hosts a site to request an email address, then invites that email via Slack. This was configured by @kylegordon. Since it's a direct link to invoke an AWS Lambda, there is a fairly horrible URL pointing to the AWS account it's hosted on.

The devtech.scot domain is owned by @rawkode who kindly setup a CNAME for us. 

An alternative is a bitly address http://bit.ly/devtechslack which exchanges the risk of the devtech.scot domain expiring to me deleting my bit.ly account.

**Comment by dougaitken** [comment]
I'm 100% OK adding this, I just wanted some more context beyond a Pull Request with no details.

My own 2¢, a landing site would help explain and market the resource - even a basic lander via GitHub pages. 

Thanks for the extra details/history @bazwilliams @b099l3

**Review by dougaitken — APPROVED** [review]

**Comment by bazwilliams** [comment]
> I'm 100% OK adding this, I just wanted some more context beyond a Pull Request with no details.
> 
> My own 2¢, a landing site would help explain and market the resource - even a basic lander via GitHub pages. 
> 
> Thanks for the extra details/history @bazwilliams @b099l3 

This is a good idea! Up to now, we've been generally word of mouth. I'll see how we can get this sorted :)

**Pull request merged**
